# 6 Repainting
nylon_price_per_sq_m = float(1.50)
paint_price_per_liter = float(14.50)
paint_thinner_price_per_liter = float(5.00)
bag_flat_price = float(0.40)
nylon_quantity = int(input())
paint_quantity = int(input())
paint_thinner_quantity = int(input())
man_hours = int(input())
nylon_price = float((nylon_quantity+int(2)) * nylon_price_per_sq_m)
paint_price = float((paint_quantity * float(1.1)) * paint_price_per_liter)
paint_thinner_price = float(paint_thinner_quantity * paint_thinner_price_per_liter)
total_material_price = float(nylon_price + paint_price + paint_thinner_price + bag_flat_price)
total_price_work = float((total_material_price * float(0.3)) * man_hours)
final_price = float(total_material_price + total_price_work)
print(f'Крайна сума: {final_price} лв.')
